import React from 'react';
import Providers from '@/redux/provider';
import './globals.css';
import 'tailwindcss/tailwind.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Toast from './components/Toast';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#dfe3ee]">
        <Providers>
          <Toast />
          {children}
        </Providers>
      </body>
    </html>
  )
}
