import React from 'react';
import Providers from '@/redux/provider';
import './globals.css';
import 'tailwindcss/tailwind.css';
// import WithAuth from "../lib/Auth";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/*<WithAuth>*/}
          <Providers>{children}</Providers>
        {/*</WithAuth>*/}
      </body>
    </html>
  )
}
